sudo: required
language: node_js
node_js:
  - 15
services:
  - docker

before_install:
  - docker build -t mohit9889/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mohit9889/docker-react npm run test

deploy:
  provider: heroku
  app: "docker-react-frontend"
  api-key: $HEROKU_API_KEY
  on:
    branch: master
